# Generated by Django 6.0.2 on 2026-02-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subject_attendance_subject_profile_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
